---
apiVersion: "v1"
kind: "Service"
metadata:
  name: traefik
  namespace: {{ namespace }}
  labels: {'k8s-app': 'traefik', 'version': 'v1'}
spec:
  selector: {'k8s-app': 'traefik'}
  type: NodePort
  ports:
    - protocol: TCP
      name: traefik
      targetPort: 80
      port: 80


