---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik
  namespace: {{ namespace }}
  labels: {'k8s-app': 'traefik', 'version': 'v1'}
spec:
  template:
    metadata:
      labels: {'k8s-app': 'traefik', 'version': 'v1'}
    spec:
      containers:
      - name: traefik
        image: {{ image }}
        volumeMounts:
          - mountPath: /etc/traefik
            name: config
        ports:
          - protocol: TCP
            name: traefik-http
            containerPort: 80
            hostPort: 80
          - protocol: TCP
            name: traefik-https
            containerPort: 443
            hostPort: 443
          - protocol: TCP
            name: traefik-board
            containerPort: 8080
      volumes:
        - name: config
          configMap:
            name: traefik
